//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SoccerEntities : DbContext
    {
        public SoccerEntities()
            : base("name=SoccerEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    
        public virtual ObjectResult<AgeRange_Result> AgeRange(Nullable<int> minimumAge, Nullable<int> maximumAge)
        {
            var minimumAgeParameter = minimumAge.HasValue ?
                new ObjectParameter("minimumAge", minimumAge) :
                new ObjectParameter("minimumAge", typeof(int));
    
            var maximumAgeParameter = maximumAge.HasValue ?
                new ObjectParameter("maximumAge", maximumAge) :
                new ObjectParameter("maximumAge", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AgeRange_Result>("AgeRange", minimumAgeParameter, maximumAgeParameter);
        }
    }
}
